
version: 2.1

orbs:
  node: circleci/node@4.5.2

jobs:
  build:
    docker:
      - image: cimg/node:14.17.4

    working_directory: ~/repo

    steps:
      - checkout

      - node/install-packages:
                pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test


workflows:
  suite:
    jobs:
      - build
